// eterLib/DIMM.h - OUR header in place of the TMP4 one.
//
// WHAT THE ORIGINAL HOLDS: **6579 lines** of COM declarations generated by
// MIDL - the interfaces `IActiveIMMApp`, `IEnumRegisterWordA/W`,
// `IActiveIMMMessagePumpOwner` and all their scaffolding. This is Active IMM,
// the Windows layer for entering Asian characters.
//
// WHY WE REPLACE IT WITH AN EMPTY FILE - and this is a measurement, not convenience:
//
//   grep over the WHOLE TMP4 tree for `IActiveIMM*`, `IEnumRegisterWord*`,
//   `REGISTERWORD*`, `CLSID_CActiveIMM*` finds them **only in DIMM.h
//   itself**. Neither `IME.cpp`, nor `UserInterface`, nor anyone else reaches
//   for any of these types.
//
// So the include in `IME.h` is accidental - exactly the same situation as
// `scriptLib/StdAfx.h` in `PRTerrainLib`: a header pulled in "because
// it might come in handy some day". It cost 22 `UserInterface` files, which
// stopped one after another on `MIDL_INTERFACE`, `IUnknown`, `REGISTERWORDA`
// and further links of the chain.
//
// AND IF IME WERE NEEDED AFTER ALL: in the browser the browser itself composes
// the characters and hands over finished text through the events `compositionstart`,
// `compositionupdate`, `compositionend`. There is nothing of the COM layer to recreate.

#pragma once
