'use strict';

const CLOSE_CODES = {
  UNKNOWN_TARGET: 4001,
  UPSTREAM_CONNECT_FAILED: 4002,
  UPSTREAM_CLOSED: 4003,
  CONNECTION_LIMIT: 4004,
  IDLE_TIMEOUT: 4005,
};

module.exports = { CLOSE_CODES };
